image: node:8.11.3

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - CI=true npm test

pages:
  stage: deploy
  script:
    - REACT_APP_STAGE=production CI=true npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
  only:
      - master # run on master branch


before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - staging
  - production

Deploy Staging:
  stage: staging
  only:
      - staging
  script:
    - ssh $SERVER_USER@$SERVER_HOSTNAME 'eval `ssh-agent -s`
            && ssh-add -k ~/.ssh/id_rsa_gitlab
            && cd /var/www/my/react_staging
            && git reset --hard
            && git pull origin staging
            && REACT_APP_STAGE=staging CI=true npm run build
            && rm -rf public
            && mv build public
            && rm .gitlab-ci.yml'

Deploy Production:
  stage: production
  only:
    - master
  script:
    - ssh $SERVER_USER@$SERVER_HOSTNAME 'eval `ssh-agent -s`
            && ssh-add -k ~/.ssh/id_rsa_gitlab
            && cd /var/www/my/prod
            && git reset --hard
            && git pull origin master
            && REACT_APP_STAGE=production CI=true npm run build
            && rm -rf public
            && mv build public
            && rm .gitlab-ci.yml'